name: epamms
description: Mysterious Santa

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  eva_icons_flutter: ^3.1.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  http: ^1.3.0
  html_unescape: ^2.0.0
  get: ^4.7.2
  random_string: ^2.3.1
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  firebase_analytics: ^12.0.2
  flutter_typeahead: ^5.2.0
  package_info_plus: ^8.3.0
  fluttertoast: ^8.2.8
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^7.2.0
  crypto: ^3.0.6
  path_provider: ^2.1.5
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.3.1
  file: ^7.0.1
  email_validator: ^3.0.0
  tutorial_coach_mark: ^1.2.12
  app_links: ^6.4.0
  #google_sign_in_android: ^7.1.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^7.0.1
  gpt_markdown: ^1.1.4
  device_info_plus: ^12.2.0
  synchronized: any
  amazing_icons: ^1.2.1
  flutter_native_splash: ^2.4.7
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.3.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  simple_barcode_scanner: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

dependency_overrides:

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/intl.csv
